extends RefCounted
const Session = preload("res://systems/demo_session.gd")
const EngineScript = preload("res://systems/combat_engine.gd")
const Fixture = preload("res://data/combat_fixture.gd")
const Status = preload("res://systems/status_system.gd")
const AI = preload("res://systems/combat_ai.gd")
var checks: Array[Dictionary] = []
func check(label: String, passed: bool) -> void: checks.append({"name":label,"passed":passed})
func run() -> Dictionary:
	checks.clear()
	var session := Session.new()
	var beast := session.principal()
	var build: Dictionary = beast.build.duplicate(true)
	build.normal[0]="range_1"; build.normal[1]="power_1"; build.normal[2]="duration_1"
	var preview: Dictionary = session.preview_build(beast.id,build)
	check("independent properties",preview.abilities[0].range==520.0 and preview.abilities[0].damage==22)
	check("close power",preview.abilities[2].damage==36 and preview.abilities[2].range==312.0)
	check("guard unchanged",preview.abilities[1].shield==24 and preview.abilities[1].range==0 and preview.abilities[1].damage==0)
	check("catalog immutable",session.catalog.skill("basic").damage==18 and session.catalog.skill("basic").range==400.0)
	check("duration incompatible instantaneous",preview.abilities[0].status_duration==0)
	session.acquire("residual_beast"); session.acquire("ranged_beast")
	build.modular=["residual","slow"]
	preview=session.preview_build(beast.id,build)
	check("DOT duration",preview.abilities[2].status_duration==18.0)
	check("slow duration",preview.abilities[3].status_duration==12.0)
	check("direct damage only",preview.abilities[2].damage==12 and preview.abilities[3].damage==7)
	check("cooldown unchanged",preview.abilities[2].cooldown==2)
	session.inventory.power_2="power";build.normal[3]="power_2"
	check("sum percentages once",session.preview_build(beast.id,build).abilities[0].damage==25)
	beast.hp=39;beast.ready_at.close=7
	check("apply preserves state",session.apply_build(beast.id,build).ok and beast.hp==39 and beast.ready_at.close==7)
	check("copies independent",session.collection[1].build.normal[0]=="")
	var old := session.export_data()
	old.erase("build_content_version");old.inventory.erase("power_1");old.inventory.erase("duration_1")
	old.collection[0].build.normal[1]="";old.collection[0].build.normal[2]=""
	old=JSON.parse_string(JSON.stringify(old))
	var restored := Session.new()
	var migration: Dictionary=restored.restore_data(old)
	check("legacy migration: "+str(migration),migration.ok and restored.inventory.has("power_1") and restored.inventory.has("duration_1"))
	check("migration preserves copy",restored.principal_id==session.principal_id and restored.principal().hp==39 and restored.principal().ready_at.close==7)
	var upgraded := restored.export_data();upgraded.inventory.erase("duration_1")
	check("migration not repeated",restored.restore_data(upgraded).ok and not restored.inventory.has("duration_1"))
	upgraded.build_content_version=2
	check("future content rejected",not restored.restore_data(upgraded).ok)
	check("shared timing",Fixture.ACTION_SECONDS==3.8 and Fixture.RESOLVE_SECONDS==2.2)
	var engine := EngineScript.new()
	var actors := Fixture.actors(0)
	for actor in actors: actor.abilities=[]
	engine.begin_encounter(actors)
	Status.apply(actors[1],"dot",0.0,-1.0,18.0)
	engine.advance(3.999);check("no early pulse",actors[1].hp==100)
	engine.advance(0.001);check("pulse at four",actors[1].hp==96)
	engine.advance(12.0);check("four pulses through sixteen",actors[1].hp==84)
	engine.advance(2.0);check("no expiry pulse",actors[1].hp==84 and not actors[1].states.has("dot"))
	Status.apply(actors[1],"dot",18.0,-1.0,18.0)
	Status.apply(actors[1],"dot",20.0,-1.0,18.0)
	check("reapply cadence",actors[1].states.dot.next==22.0 and actors[1].states.dot.expires==38.0)
	check("equivalent refresh not counted twice",Status.additional_dot(actors[1],20.0,18.0)==0.0)
	check("extension only extra pulses",Status.additional_dot(actors[1],24.0,18.0)==4.0)
	Status.apply(actors[0],"slow",20.0,-1.0,12.0)
	check("slow derived duration intensity",actors[0].states.slow.expires==32.0 and Status.speed(actors[0],20.0)==7.5)
	check("slow expires",Status.speed(actors[0],32.0)==10.0)
	engine.free()
	engine=EngineScript.new();actors=Fixture.actors(0)
	actors[0].abilities=[]
	actors[1].abilities=[session.catalog.skill("slow"),session.catalog.skill("far")]
	actors[0].position=Vector2.ZERO;actors[1].position=Vector2(200,0)
	engine.begin_encounter(actors)
	check("intention starts with charge",engine.intentions.has(actors[1].id) and engine.intentions[actors[1].id].provisional)
	var unchanged := engine.snapshot()
	for index in 200: engine.query_intention(actors[1].id)
	check("queries do not mutate",engine.snapshot()==unchanged)
	actors[0].atb=49.0
	engine.intentions_dirty=true;engine.refresh_intentions()
	check("offense below control threshold",engine.intentions[actors[1].id].skill.id=="far")
	engine.advance(0.1)
	check("control threshold refresh",engine.intentions[actors[1].id].skill.id=="slow")
	var update_count: int=engine.intention_updates
	for index in 20: engine.advance(0.001)
	check("no choice recalculation every frame",engine.intention_updates==update_count)
	actors[0].atb=100.0;actors[0].ready_time=engine.combat_clock
	actors[1].atb=100.0;actors[1].ready_time=engine.combat_clock+0.001
	engine.choose_next();engine.intentions_dirty=true;engine.refresh_intentions()
	check("ready queued enemy retains intention",engine.intentions.has(actors[1].id))
	var anticipated := engine.query_intention(actors[1].id)
	engine.advance(3.8)
	check("unchanged intent matches dispatch",engine.pending.actor_id==actors[1].id and engine.pending.skill.id==anticipated.skill.id)
	check("executing no provisional intent",not engine.intentions.has(actors[1].id))
	engine.apply_damage(actors[1],1000)
	check("death clears intentions",engine.intentions.is_empty())
	engine.free()
	var world := preload("res://data/world_fixture.gd").populate()
	check("distinct encounter kits",world[1].abilities[2].id=="residual" and world[3].abilities[2].id=="slow" and world[4].abilities[2].id=="close")
	check("distinct speeds",world[1].speed==8 and world[3].speed==12 and world[4].speed==10)
	var arena := preload("res://ui/arena_view.gd").new()
	var smoke_engine := EngineScript.new()
	smoke_engine.start(0);arena.combat=smoke_engine;arena.size=Vector2(760,600)
	var label_position: Vector2=arena.actor_label_point(smoke_engine.actors[0],"Principal",16,Vector2(0,-62))
	check("labels safe before first draw",label_position.is_finite())
	check("projection uses allocated battlefield",arena.projection_height()==600.0)
	arena.free();smoke_engine.free()
	var variants: Array=[{"modular":["close","far"],"mods":["power_1","range_1"]},{"modular":["residual","far"],"mods":["duration_1","range_1"]},{"modular":["slow","close"],"mods":["duration_1","power_1"]}]
	for variant in variants:
		var draft: Dictionary=session.builds.empty_build(variant.modular)
		for index in variant.mods.size(): draft.normal[index]=variant.mods[index]
		check("diagnostic variant "+str(variant.modular),session.validate_build(beast.id,draft).ok)
	var failures: Array = checks.filter(func(row):return not row.passed)
	return {"passed":failures.is_empty(),"count":checks.size(),"checks":checks,"failures":failures}
