extends RefCounted
const Matrix=preload("res://systems/combat_matrix.gd")
const Screen=preload("res://ui/combat_screen.gd")
var checks: Array=[]
func check(label: String, condition: bool) -> void: checks.append({"name":label,"passed":condition})
func run() -> Dictionary:
	var service:=Matrix.new()
	var engine:=preload("res://systems/combat_engine.gd").new();engine.start(2)
	var before: Dictionary=engine.snapshot()
	check("closed outside battle",not service.open("main",engine.actors))
	service.sync(true,engine.actors)
	check("opens main",service.open("main",engine.actors))
	check("initial positions",service.current().positions==[1,3,5])
	check("invalid actor rejected",not service.open("missing",engine.actors))
	service.rotate(-1)
	check("rotation one step",service.current().positions==[0,3,5])
	service.close();service.open("main",engine.actors)
	check("close retains progress",service.current().positions==[0,3,5])
	var enemy_id: String=engine.actors[1].id
	service.open(enemy_id,engine.actors);service.rotate(1)
	check("enemy independent",service.current().positions==[2,3,5])
	service.open("main",engine.actors)
	check("switch restores main",service.current().positions==[0,3,5])
	check("single open owner",service.owner_id=="main" and service.matrices.size()==2)
	service.select_ring(1)
	for i in 3: service.rotate(-1)
	service.select_ring(2)
	for i in 5: service.rotate(-1)
	check("all aligned",service.current().resolved and service.current().positions==[0,0,0])
	service.rotate(1);check("resolved remains visible stable",service.current().positions==[0,0,0])
	var detached: Dictionary=service.snapshot();detached.matrices.main.positions[0]=7
	check("snapshot detached",service.current().positions[0]==0)
	check("no engine mutation",engine.snapshot()==before)
	service.reset();service.rotate(-1);service.rotate(-1)
	check("wrap eight positions",service.current().positions[0]==7)
	service.select_ring(9);check("invalid selection ignored",service.current().selected==0)
	service.rotate(9);check("invalid rotation ignored",service.current().positions[0]==7)
	service.open(enemy_id,engine.actors);engine.actors[1].retired=true;service.sync(true,engine.actors)
	check("retirement closes owner",service.owner_id=="")
	check("retirement discards state",not service.matrices.has(enemy_id))
	service.open("main",engine.actors);engine.actors[0].hp=0;service.sync(true,engine.actors)
	check("death closes owner",service.owner_id=="")
	service.sync(false,engine.actors);check("battle end clears state",service.matrices.is_empty() and not service.active)
	engine.actors[0].hp=100;service.sync(true,engine.actors);service.open("main",engine.actors)
	check("new encounter fresh",service.current().positions==[1,3,5] and service.encounter==2)
	var screen:=Screen.new();check("screen compiles",screen.matrix!=null);screen.free();engine.free()
	var failures: Array=checks.filter(func(row):return not row.passed)
	return {"passed":failures.is_empty(),"count":checks.size(),"checks":checks,"failures":failures}
